10-22 18:04:28 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Table "PLAY_EVOLUTIONS" not found; SQL statement:
select id, hash, apply_script, revert_script, state, last_problem from play_evolutions where state like 'applying_%' [42102-168]
10-23 09:41:50 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DELETE *[*] FROM USERS"; expected "identifier"; SQL statement:
DELETE * FROM USERS [42001-168]
10-23 09:43:19 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM USERS_SECURITY_ROLE 

DELETE FROM[*] USERS_SECURITY_ROLE WHERE ID = 33"; SQL statement:
SELECT * FROM USERS_SECURITY_ROLE 

DELETE FROM USERS_SECURITY_ROLE WHERE ID = 33 [42000-168]
10-23 09:43:27 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "ID" not found; SQL statement:
DELETE FROM USERS_SECURITY_ROLE WHERE ID = 33 [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.command.dml.Delete.prepare(Delete.java:125)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Thread.java:724)
10-23 09:43:39 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "USER_ID" not found; SQL statement:
DELETE FROM USERS_SECURITY_ROLE WHERE USER_ID = 33 [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.command.dml.Delete.prepare(Delete.java:125)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Thread.java:724)
10-23 09:52:34 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "USERS_ID" not found; SQL statement:
DELETE FROM LINKED_ACCOUNT  WHERE USERS_ID = 67 [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.command.dml.Delete.prepare(Delete.java:125)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Thread.java:724)
03-19 11:23:16 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "USERS[*] SELECT * FROM LINKED_ACCOUNT"; expected "UPDATE, {"; SQL statement:
USERS SELECT * FROM LINKED_ACCOUNT [42001-168]
03-19 15:41:11 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO AUTHTOKEN ('USER'[*], 'PROVIDER', 'TOKEN') VALUES ('?', '?','?');"; expected "identifier"; SQL statement:
INSERT INTO AUTHTOKEN ('USER', 'PROVIDER', 'TOKEN') VALUES ('?', '?','?'); [42001-168]
03-19 15:41:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO AUTHTOKEN ('USER'[*], 'PROVIDER', 'TOKEN') VALUES ('?', '?','?');"; expected "identifier"; SQL statement:
INSERT INTO AUTHTOKEN ('USER', 'PROVIDER', 'TOKEN') VALUES ('?', '?','?'); [42001-168]
03-19 15:43:35 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO AUTHTOKEN ('USER'[*], 'PROVIDER', 'TOKEN') VALUES ('?', '?','?');"; expected "identifier"; SQL statement:
INSERT INTO AUTHTOKEN ('USER', 'PROVIDER', 'TOKEN') VALUES ('?', '?','?'); [42001-168]
03-19 15:45:10 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO AUTHTOKEN ('USER'[*], 'PROVIDER', 'TOKEN') VALUES ('?', '?','?');"; expected "identifier"; SQL statement:
INSERT INTO AUTHTOKEN ('USER', 'PROVIDER', 'TOKEN') VALUES ('?', '?','?'); [42001-168]
03-19 15:50:59 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO AUTHTOKEN ('USER'[*], 'PROVIDER', 'TOKEN') VALUES ('1', 'facebook','1')"; expected "identifier"; SQL statement:
INSERT INTO AUTHTOKEN ('USER', 'PROVIDER', 'TOKEN') VALUES ('1', 'facebook','1') [42001-168]
03-19 15:55:02 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Invalid value "1" for parameter "parameterIndex" [90008-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:215)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1284)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:340)
	at com.jolbox.bonecp.PreparedStatementHandle.setString(PreparedStatementHandle.java:1029)
	at models.AuthToken.updateStatus(AuthToken.java:55)
	at controllers.Application.restricted(Application.java:49)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$6$$anonfun$apply$6.apply(routes_routing.scala:217)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$6$$anonfun$apply$6.apply(routes_routing.scala:217)
	at play.core.Router$HandlerInvoker$$anon$6$$anon$2.invocation(Router.scala:193)
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:373)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:50)
	at play.GlobalSettings$1.call(GlobalSettings.java:63)
	at be.objectify.deadbolt.java.actions.RestrictAction.applyRestriction(RestrictAction.java:57)
	at be.objectify.deadbolt.java.actions.AbstractRestrictiveAction.execute(AbstractRestrictiveAction.java:44)
	at be.objectify.deadbolt.java.actions.AbstractDeadboltAction.call(AbstractDeadboltAction.java:99)
	at play.core.j.JavaAction$$anon$2.apply(JavaAction.scala:80)
	at play.core.j.JavaAction$$anon$2.apply(JavaAction.scala:79)
	at play.libs.F$Promise$PromiseActor.onReceive(F.java:425)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425)
	at akka.actor.ActorCell.invoke(ActorCell.scala:386)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230)
	at akka.dispatch.Mailbox.run(Mailbox.scala:212)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:502)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
03-19 15:59:29 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Invalid value "1" for parameter "parameterIndex" [90008-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:215)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1284)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:340)
	at com.jolbox.bonecp.PreparedStatementHandle.setString(PreparedStatementHandle.java:1029)
	at models.AuthToken.updateStatus(AuthToken.java:55)
	at controllers.Application.restricted(Application.java:49)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$6$$anonfun$apply$6.apply(routes_routing.scala:217)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$6$$anonfun$apply$6.apply(routes_routing.scala:217)
	at play.core.Router$HandlerInvoker$$anon$6$$anon$2.invocation(Router.scala:193)
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:373)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:50)
	at play.GlobalSettings$1.call(GlobalSettings.java:63)
	at be.objectify.deadbolt.java.actions.RestrictAction.applyRestriction(RestrictAction.java:57)
	at be.objectify.deadbolt.java.actions.AbstractRestrictiveAction.execute(AbstractRestrictiveAction.java:44)
	at be.objectify.deadbolt.java.actions.AbstractDeadboltAction.call(AbstractDeadboltAction.java:99)
	at play.core.j.JavaAction$$anon$2.apply(JavaAction.scala:80)
	at play.core.j.JavaAction$$anon$2.apply(JavaAction.scala:79)
	at play.libs.F$Promise$PromiseActor.onReceive(F.java:425)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425)
	at akka.actor.ActorCell.invoke(ActorCell.scala:386)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230)
	at akka.dispatch.Mailbox.run(Mailbox.scala:212)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:502)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
03-19 16:01:51 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: Invalid value "1" for parameter "parameterIndex" [90008-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:215)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1284)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:340)
	at com.jolbox.bonecp.PreparedStatementHandle.setString(PreparedStatementHandle.java:1029)
	at models.AuthToken.updateStatus(AuthToken.java:55)
	at controllers.Application.restricted(Application.java:49)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$6$$anonfun$apply$6.apply(routes_routing.scala:217)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$6$$anonfun$apply$6.apply(routes_routing.scala:217)
	at play.core.Router$HandlerInvoker$$anon$6$$anon$2.invocation(Router.scala:193)
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:373)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:50)
	at play.GlobalSettings$1.call(GlobalSettings.java:63)
	at be.objectify.deadbolt.java.actions.RestrictAction.applyRestriction(RestrictAction.java:57)
	at be.objectify.deadbolt.java.actions.AbstractRestrictiveAction.execute(AbstractRestrictiveAction.java:44)
	at be.objectify.deadbolt.java.actions.AbstractDeadboltAction.call(AbstractDeadboltAction.java:99)
	at play.core.j.JavaAction$$anon$2.apply(JavaAction.scala:80)
	at play.core.j.JavaAction$$anon$2.apply(JavaAction.scala:79)
	at play.libs.F$Promise$PromiseActor.onReceive(F.java:425)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425)
	at akka.actor.ActorCell.invoke(ActorCell.scala:386)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230)
	at akka.dispatch.Mailbox.run(Mailbox.scala:212)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:502)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
03-19 16:09:09 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: Table "AUTHTOKEN" not found; SQL statement:
SELECT * FROM AUTHTOKEN WHERE USER=? AND PROVIDER=?  [42102-168]
03-19 16:10:00 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: Table "AUTHTOKEN" not found; SQL statement:
SELECT * FROM AUTHTOKEN WHERE USER=? AND PROVIDER=?  [42102-168]
03-26 10:54:46 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "FACEBOOK" not found; SQL statement:
INSERT INTO AUTHTOKEN (USER, PROVIDER, TOKEN) VALUES (1,facebook,jhbjhb) [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.command.dml.Insert.prepare(Insert.java:231)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Thread.java:744)
03-26 10:55:12 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO AUTHTOKEN (ID, USER, PROVIDER, TOKEN) VALUES (,[*]1,2,3)"; expected "), DEFAULT, NOT, EXISTS, SELECT, FROM"; SQL statement:
INSERT INTO AUTHTOKEN (ID, USER, PROVIDER, TOKEN) VALUES (,1,2,3) [42001-168]
03-26 15:32:50 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "USERS[*] SELECT * FROM USERS"; expected "UPDATE, {"; SQL statement:
USERS SELECT * FROM USERS [42001-168]
